# Generated by Django 2.2.9 on 2022-10-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20221004_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.FilePathField(unique=True),
        ),
    ]
